---
title: "Vertebrados de Curridabat"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
library(sf)
library(leaflet)
library(knitr)
library(kableExtra)
library(dplyr)

# Registros de presencia de Chordata en la GAM
gam_chordata <- 
  st_read(
    "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos/master/biodiversidad/presencia/gam_chordata.geojson"
  ) %>%
  filter(phylum == "Chordata")

# URL base del servicio WFS IGN 1:5mil
url_base_wfs_ign_5mil <- "http://geos.snitcr.go.cr/be/IGN_5/wfs?"
# URL de las solicitud de la capa de cantones
solicitud_cantones_wfs <- "request=GetFeature&service=WFS&version=2.0.0&typeName=IGN_5:limitecantonal_5k&outputFormat=application/json"

# Cantón
canton_limite <-
  st_read(paste0(url_base_wfs_ign_5mil, solicitud_cantones_wfs)) %>%
  filter(canton == "Curridabat") %>%
  st_transform(4326)

canton_chordata <- gam_chordata[canton_limite, , op = st_within]


# Registros de presencia de Mammalia
canton_mammalia <- 
  canton_chordata %>%
  filter(class=="Mammalia")

# Registros de presencia de Amphibia
canton_amphibia <- 
  canton_chordata %>%
  filter(class=="Amphibia")

# Registros de presencia de Reptilia
canton_reptilia <- 
  canton_chordata %>%
  filter(class=="Reptilia")
```

Column {.sidebar data-width=600}
-----------------------------------------------------------------------

### Mapa de distribución

```{r}
m <- leaflet(canton_limite) %>% 
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addPolygons(group = "Límite cantonal") %>%
  addCircleMarkers(data = canton_mammalia,
                   stroke = T,
                   radius = 6,
                   fillColor = 'brown',
                   fillOpacity = 1,
                   group = "Registros de Mammalia",
                   popup = paste(canton_mammalia$locality, 
                                 canton_mammalia$year, 
                                 canton_mammalia$order,
                                 canton_mammalia$species,
                                 sep = '<br/>'
                           )
  ) %>%
  addCircleMarkers(data = canton_amphibia,
                   stroke = T,
                   radius = 6,
                   fillColor = 'green',
                   fillOpacity = 1,
                   group = "Registros de Amphibia",
                   popup = paste(canton_amphibia$locality, 
                                 canton_amphibia$year, 
                                 canton_amphibia$order,
                                 canton_amphibia$species,
                                 sep = '<br/>'
                           )
  ) %>%  
  addCircleMarkers(data = canton_reptilia,
                   stroke = T,
                   radius = 6,
                   fillColor = 'orange',
                   fillOpacity = 1,
                   group = "Registros de Reptilia",
                   popup = paste(canton_reptilia$locality, 
                                 canton_reptilia$year, 
                                 canton_reptilia$order,
                                 canton_reptilia$species,
                                 sep = '<br/>'
                           )
  ) %>%    
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI"),
    overlayGroups = c("Límite cantonal", "Registros de Mammalia", "Registros de Amphibia", "Registros de Reptilia"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$Stamen.TonerLite
  )

# Despliegue del mapa
m
```

Row {data-height=200}
-------------------------------------
### especies de vertebrados
```{r}
valueBox(length(unique(canton_chordata[["species"]])), icon = "fa-pencil")
```

### especies de _Mammalia_
```{r}
valueBox(length(unique(canton_mammalia[["species"]])), icon = "fa-pencil")
```

### especies de _Amphibia_
```{r}
valueBox(length(unique(canton_amphibia[["species"]])), icon = "fa-pencil")
```

### especies de _Reptilia_
```{r}
valueBox(length(unique(canton_reptilia[["species"]])), icon = "fa-pencil")
```

Row {data-height=800}
-------------------------------------
### Registros de presencia
```{r}
canton_chordata %>%
  select(Clase=class, Orden=order, Familia=family, Género=genus, Especie=species, Año=year, Localidad=locality) %>%
  arrange(Clase, Orden, Familia, Especie) %>%
  st_drop_geometry() %>%
  kable()%>%
  kable_styling() %>%
  scroll_box(
    width = "900px", 
    height = "500px", 
    fixed_thead = TRUE
  )
```

